# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ تسليم العهدة'),
        ),
        migrations.AlterField(
            model_name='assetcondition',
            name='as_of_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='assetcustodian',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='disposal_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاستبعاد الفعلي'),
        ),
        migrations.AlterField(
            model_name='assetimpairment',
            name='impairment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاضمحلال'),
        ),
        migrations.AlterField(
            model_name='assetinspection',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفحص'),
        ),
        migrations.AlterField(
            model_name='assetinventoryaudit',
            name='audit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الجرد'),
        ),
        migrations.AlterField(
            model_name='assetmaintenanceplaceholder',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الصيانة والإصلاح'),
        ),
        migrations.AlterField(
            model_name='assetretirement',
            name='retirement_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التقاعد'),
        ),
        migrations.AlterField(
            model_name='assetrevaluation',
            name='revaluation_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ إعادة التقييم'),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ طلب النقل'),
        ),
    ]
