# Generated by Django 5.2.15 on 2026-07-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractitem',
            options={'verbose_name': 'بند عقد', 'verbose_name_plural': 'بنود عقود المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='contractrenewal',
            options={'verbose_name': 'تجديد عقد', 'verbose_name_plural': 'تجديدات العقود'},
        ),
        migrations.AlterModelOptions(
            name='procurementaudit',
            options={'verbose_name': 'سجل تدقيق المشتريات', 'verbose_name_plural': 'سجلات تدقيق المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='procurementstatistics',
            options={'verbose_name': 'إحصائيات المشتريات', 'verbose_name_plural': 'إحصائيات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchasebudget',
            options={'verbose_name': 'حجز موازنة', 'verbose_name_plural': 'حجوزات موازنات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchasecontract',
            options={'verbose_name': 'عقد مشتريات', 'verbose_name_plural': 'عقود المشتريات والاتفاقيات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'أمر شراء', 'verbose_name_plural': 'أوامر الشراء (PO)'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'بند أمر شراء', 'verbose_name_plural': 'بنود أوامر الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderrevision',
            options={'verbose_name': 'مراجعة أمر شراء', 'verbose_name_plural': 'تعديلات ومراجعات أوامر الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaseplan',
            options={'verbose_name': 'خطة شراء', 'verbose_name_plural': 'خطط الشراء السنوية'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'طلب شراء', 'verbose_name_plural': 'طلبات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestapproval',
            options={'verbose_name': 'اعتماد طلب شراء', 'verbose_name_plural': 'اعتمادات طلبات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'verbose_name': 'بند طلب شراء', 'verbose_name_plural': 'بنود طلبات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchasesettings',
            options={'verbose_name': 'إعدادات المشتريات', 'verbose_name_plural': 'إعدادات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'عرض أسعار', 'verbose_name_plural': 'عروض أسعار الموردين'},
        ),
        migrations.AlterModelOptions(
            name='quotationcomparison',
            options={'verbose_name': 'مقارنة عروض الأسعار', 'verbose_name_plural': 'مقارنات وتحليلات عروض الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': 'بند عرض أسعار', 'verbose_name_plural': 'بنود عروض الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'verbose_name': 'طلب عروض أسعار', 'verbose_name_plural': 'طلبات عروض الأسعار (RFQ)'},
        ),
        migrations.AlterModelOptions(
            name='rfqitem',
            options={'verbose_name': 'بند طلب أسعار', 'verbose_name_plural': 'بنود طلبات عروض الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'المورد', 'verbose_name_plural': 'الموردون'},
        ),
        migrations.AlterModelOptions(
            name='vendoraward',
            options={'verbose_name': 'ترسية المشتريات', 'verbose_name_plural': 'ترسية المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='vendorbankaccount',
            options={'verbose_name': 'حساب بنكي للمورد', 'verbose_name_plural': 'الحسابات البنكية للموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendorblacklist',
            options={'verbose_name': 'القائمة السوداء', 'verbose_name_plural': 'القائمة السوداء للموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'verbose_name': 'فئة الموردين', 'verbose_name_plural': 'فئات الموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendorcontact',
            options={'verbose_name': 'جهة اتصال المورد', 'verbose_name_plural': 'جهات اتصال الموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendordocument',
            options={'verbose_name': 'مستند المورد', 'verbose_name_plural': 'مستندات الموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendorevaluation',
            options={'verbose_name': 'تقييم المورد', 'verbose_name_plural': 'تقييمات الموردين'},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'verbose_name': 'أداء المورد', 'verbose_name_plural': 'مؤشرات أداء الموردين'},
        ),
    ]
