# Generated by Django 5.2.15 on 2026-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='journal_entry_id',
            field=models.UUIDField(blank=True, help_text='قيد اليومية المرحّل لفاتورة المورّد بالمالية', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, help_text='رقم فاتورة المورّد المستلمة', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='payable_gl_account_id',
            field=models.UUIDField(blank=True, help_text='حساب ذمم الموردين الدائنة في شجرة حسابات المالية — يُرحَّل عليه قيد فاتورة المورّد', null=True),
        ),
    ]
