# Generated by Django 5.2.15 on 2026-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_journal_entry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
