# Generated by Django 5.2.15 on 2026-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_contractrenewal_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='inventory_item_id',
            field=models.UUIDField(blank=True, help_text='الصنف المخزني المقابل — يُملأ حين يكون البند صنفاً معرّفاً في المخزون', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='inventory_item_id',
            field=models.UUIDField(blank=True, help_text='الصنف المخزني المقابل — يُملأ حين يكون البند صنفاً معرّفاً في المخزون', null=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='inventory_item_id',
            field=models.UUIDField(blank=True, help_text='الصنف المخزني المقابل — يُملأ حين يكون البند صنفاً معرّفاً في المخزون', null=True),
        ),
    ]
