# Generated by Django 5.2.15 on 2026-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorderitem_inventory_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_voucher_id',
            field=models.UUIDField(blank=True, help_text='سند الصرف الذي سُدّد به هذا الأمر في المالية', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد ومصدر للمورد'), ('issued', 'مرسل ومؤكد'), ('completed', 'مكتمل ومستلم بالكامل'), ('paid', 'مسدَّد للمورّد'), ('cancelled', 'ملغى')], default='draft', max_length=30),
        ),
    ]
