# Generated by Django 5.2.15 on 2026-07-03 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور ومفعل'), ('archived', 'مؤرشف')], default='draft', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('branch_scope', models.UUIDField(blank=True, null=True)),
                ('campus_scope', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('approval_status', models.CharField(choices=[('pending', 'معلق الموافقة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='approved', max_length=30)),
            ],
            options={
                'db_table': 'nebras_rules',
            },
        ),
        migrations.CreateModel(
            name='RuleAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=100)),
                ('action_taken', models.CharField(max_length=100)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nebras_rule_audits',
            },
        ),
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_rule_categories',
            },
        ),
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_rule_templates',
            },
        ),
        migrations.CreateModel(
            name='RuleVariable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('data_type', models.CharField(default='string', max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'nebras_rule_variables',
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('allow', 'السماح بالعملية'), ('deny', 'رفض وحجب العملية'), ('calculate', 'احتساب معادلة'), ('notify', 'إرسال إشعار وتنبيه')], max_length=50)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_actions',
            },
        ),
        migrations.CreateModel(
            name='RuleApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_approvals',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules.rulecategory'),
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_executions',
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('log_level', models.CharField(default='info', max_length=30)),
                ('message', models.TextField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rules.ruleexecution')),
            ],
            options={
                'db_table': 'nebras_rule_execution_logs',
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='rules.rulecategory')),
            ],
            options={
                'db_table': 'nebras_rule_groups',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='rules.rulegroup'),
        ),
        migrations.CreateModel(
            name='RuleHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('modified_by', models.UUIDField(blank=True, null=True)),
                ('change_summary', models.TextField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_history',
            },
        ),
        migrations.CreateModel(
            name='RuleParameter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('param_type', models.CharField(max_length=50)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_parameters',
            },
        ),
        migrations.CreateModel(
            name='RulePriority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('priority_level', models.IntegerField(default=1)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_config', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_priorities',
            },
        ),
        migrations.CreateModel(
            name='RuleSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('cron_expression', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_schedules',
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('equals', 'يساوي =='), ('not_equals', 'لا يساوي !='), ('greater_than', 'أكبر من >'), ('less_than', 'أصغر من <'), ('greater_or_equal', 'أكبر أو يساوي >='), ('less_or_equal', 'أصغر أو يساوي <='), ('between', 'بين X و Y'), ('contains', 'يحتوي على')], max_length=50)),
                ('value_to_compare', models.CharField(max_length=255)),
                ('logical_gate', models.CharField(default='AND', max_length=10)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rule')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rulevariable')),
            ],
            options={
                'db_table': 'nebras_rule_conditions',
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('version_number', models.IntegerField()),
                ('change_log', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rules.rule')),
            ],
            options={
                'db_table': 'nebras_rule_versions',
            },
        ),
    ]