# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_binlocation_goodsissue_goodsissueitem_goodsreceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ صرف البند'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاستلام الفعلي'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ تسجيل الحركة'),
        ),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
    ]
