# Generated by Django 5.2.15 on 2026-07-18 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_goodsissue_issue_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransferItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='الكمية المحوَّلة')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='تكلفة الوحدة وقت التحويل')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='الصنف المحوَّل')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytransfer', verbose_name='التحويل')),
            ],
            options={
                'verbose_name': 'بند تحويل مخزني',
                'verbose_name_plural': 'بنود التحويلات المخزنية',
                'db_table': 'nebras_inventory_transfer_items',
            },
        ),
    ]
