# Generated by Django 5.2.15 on 2026-07-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AlterModelOptions(
            name='employeecontract',
            options={'verbose_name': 'عقد موظف', 'verbose_name_plural': 'عقود الموظفين'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.UUIDField(db_index=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الراتب'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='بنود العقد'),
        ),
    ]
