# Generated by Django 5.2.15 on 2026-07-04 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('status', models.CharField(db_index=True, default='present', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_attendance_student_daily',
                'unique_together': {('student_id', 'date')},
            },
        ),
    ]
