# Generated by Django 5.1.15 on 2026-07-19 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentdailyattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('period_code', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_attendance_sheets',
                'unique_together': {('period_code', 'tenant_id')},
            },
        ),
    ]
