# Generated by Django 5.1.15 on 2026-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='latitude',
            field=models.FloatField(default=24.7136, help_text='إحداثيات خط العرض للمدرسة'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='longitude',
            field=models.FloatField(default=46.6753, help_text='إحداثيات خط الطول للمدرسة'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='radius_meters',
            field=models.IntegerField(default=150, help_text='نصف قطر النطاق المسموح بالمتر'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='verification_method',
            field=models.CharField(default='gps_biometric', max_length=50),
        ),
    ]
