# Generated by Django 5.2.15 on 2026-07-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'تكليف تدريسي', 'verbose_name_plural': 'التكليفات التدريسية'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'ملف معلم', 'verbose_name_plural': 'ملفات المعلمين'},
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='section_id',
            field=models.UUIDField(db_index=True, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject_id',
            field=models.UUIDField(db_index=True, verbose_name='المادة الدراسية'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacherprofile', verbose_name='المعلم'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(max_length=255, verbose_name='المؤهل العلمي'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(db_index=True, max_length=255, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
