# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationhistory',
            options={'verbose_name': 'سجل إشعار', 'verbose_name_plural': 'سجل الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'قالب إشعار', 'verbose_name_plural': 'قوالب الإشعارات'},
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='body',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='channel',
            field=models.CharField(db_index=True, max_length=20, verbose_name='القناة'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='recipient',
            field=models.CharField(db_index=True, max_length=255, verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد الإرسال'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(verbose_name='قالب المحتوى'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(db_index=True, max_length=20, verbose_name='القناة'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
    ]
