# Generated by Django 5.1.15 on 2026-07-27 14:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='المستخدم')),
                ('token', models.TextField(verbose_name='FCM Token')),
                ('platform', models.CharField(default='android', max_length=20, verbose_name='نظام التشغيل')),
                ('device_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'رمز جهاز التنبيهات',
                'verbose_name_plural': 'رموز أجهزة التنبيهات',
                'db_table': 'nebras_device_tokens',
                'unique_together': {('tenant_id', 'user_id', 'token')},
            },
        ),
    ]
