# Generated by Django 5.2.15 on 2026-07-02 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_master_categories',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('value_ar', models.CharField(max_length=255)),
                ('value_en', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_data.mastercategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_data.masteritem')),
            ],
            options={
                'db_table': 'nebras_master_items',
            },
        ),
        migrations.CreateModel(
            name='MasterTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('translated_value', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='master_data.masteritem')),
            ],
            options={
                'db_table': 'nebras_master_translations',
            },
        ),
        migrations.AddIndex(
            model_name='masteritem',
            index=models.Index(fields=['tenant_id', 'is_active', 'effective_date', 'expiry_date'], name='nebras_mast_tenant__c169e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masteritem',
            unique_together={('tenant_id', 'category', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='mastertranslation',
            unique_together={('tenant_id', 'item', 'language_code')},
        ),
    ]