# Generated by Django 5.2.15 on 2026-07-02 13:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('file_asset_id', models.UUIDField(db_index=True, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_provider', models.CharField(default='local', max_length=50)),
                ('storage_path', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('file_category', models.CharField(default='general', max_length=100)),
            ],
            options={
                'db_table': 'platform_attachments_metadata',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], default='info', max_length=20)),
            ],
            options={
                'db_table': 'platform_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('job_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد التشغيل'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_background_jobs',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(default='published', max_length=30)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_event_logs',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('flag_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=100)),
                ('target_users', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'platform_feature_flags',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('whatsapp', 'واتساب'), ('push', 'تنبيه فوري'), ('in_app', 'داخل التطبيق'), ('sms', 'رسالة نصية قصيرة')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('read', 'تمت القراءة')], default='pending', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_notifications',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('config_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('config_value', models.JSONField(default=dict)),
                ('config_type', models.CharField(default='global', max_length=50)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'platform_system_configurations',
            },
        ),
    ]