# Generated by Django 5.2.15 on 2026-07-03 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_facultymember_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTimetable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campus_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('review', 'تحت المراجعة'), ('approved', 'مقبول ومعتمد'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'nebras_academic_timetables',
            },
        ),
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'nebras_timetable_class_periods',
            },
        ),
        migrations.CreateModel(
            name='SubjectDistribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('grade_section_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('total_required_periods', models.IntegerField(default=5)),
                ('distributed_periods', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'nebras_timetable_subject_distributions',
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nebras_timetable_templates',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('grade_section_id', models.UUIDField(db_index=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_class_schedules',
            },
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('room_id', models.UUIDField(db_index=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_room_schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_approvals',
            },
        ),
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('change_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_history',
            },
        ),
        migrations.CreateModel(
            name='SchedulePublish',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('published_by', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_publications',
            },
        ),
        migrations.CreateModel(
            name='ScheduleStatistics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('total_lessons', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('teacher_utilization_rate', models.FloatField(default=0.0)),
                ('room_utilization_rate', models.FloatField(default=0.0)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_statistics',
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.facultymember')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_teacher_schedules',
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('grade_section_id', models.UUIDField(db_index=True)),
                ('weekly_periods', models.IntegerField(default=4)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignments', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_timetable_teaching_assignments',
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('max_weekly_hours', models.IntegerField(default=24)),
                ('max_daily_hours', models.IntegerField(default=6)),
                ('assigned_weekly_hours', models.IntegerField(default=0)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_timetable_teaching_loads',
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('subject_id', models.UUIDField(db_index=True, help_text='الربط مع موديول المواد الدراسية')),
                ('room_id', models.UUIDField(db_index=True, help_text='الربط مع القاعات في الماستر داتا')),
                ('grade_section_id', models.UUIDField(db_index=True, help_text='الربط مع الفصل/الشعبة الدراسية')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='faculty.facultymember')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_entries',
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('version_number', models.IntegerField()),
                ('created_by_user', models.UUIDField(blank=True, null=True)),
                ('change_log', models.TextField(blank=True, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='timetable.academictimetable')),
            ],
            options={
                'db_table': 'nebras_timetable_versions',
            },
        ),
    ]
