# Generated by Django 5.1.15 on 2026-09-16 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_facultymember_single_source_of_truth'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSubstitution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('substitution_date', models.DateField(help_text='تاريخ يوم حصة الاحتياط الفعلي')),
                ('reason', models.CharField(default='غياب المعلم الأصلي', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الاعتماد'), ('confirmed', 'معتمد ومؤكد'), ('completed', 'منفذ ومكتمل'), ('cancelled', 'ملغي')], default='confirmed', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetableentry')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_substitutions', to='faculty.facultymember')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_timetable_substitutions',
                'ordering': ['-substitution_date'],
            },
        ),
    ]
