# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmspage',
            options={'verbose_name': 'صفحة محتوى', 'verbose_name_plural': 'صفحات المحتوى'},
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
