# Generated by Django 5.2.15 on 2026-07-01 13:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user_id', models.UUIDField(db_index=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
    ]