# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'verbose_name': 'محادثة ذكاء اصطناعي', 'verbose_name_plural': 'محادثات الذكاء الاصطناعي'},
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='prompt',
            field=models.TextField(verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='response',
            field=models.TextField(verbose_name='الرد'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='tokens_used',
            field=models.IntegerField(default=0, verbose_name='عدد الرموز المستهلكة'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='user_id',
            field=models.UUIDField(db_index=True, verbose_name='المستخدم'),
        ),
    ]
