# Generated by Django 5.2.15 on 2026-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiconversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='المستخدم'),
        ),
    ]
