# Generated by Django 5.2.15 on 2026-07-01 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id', 'timestamp'], name='audit_logs_tenant__eb751d_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_logs_user_id_88267f_idx')],
            },
        ),
    ]