# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل مراقبة', 'verbose_name_plural': 'سجلات المراقبة والتدقيق'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('restore', 'استرجاع'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('permission_change', 'تغيير صلاحيات')], db_index=True, max_length=20, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='اسم النموذج'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='القيم الجديدة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='معرف السجل'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='القيم القديمة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='المستأجر'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='بيانات المتصفح'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='المستخدم'),
        ),
    ]
