version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nebras_redis
    restart: always
    networks:
      - nebras_network

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: nebras_frontend
    volumes:
      - frontend_dist:/dist
    networks:
      - nebras_network

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: nebras_backend
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ../backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:Scanreg2restore@nebras-db.clggsiykkaoa.eu-north-1.rds.amazonaws.com:5432/nebras_db?sslmode=require}
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://13.53.124.237,https://13.53.124.237
      - SECRET_KEY=django-insecure-nebras-super-prod-aws-key-2026
      - EVOLUTION_API_URL=http://13.61.13.0:8050
      - EVOLUTION_API_KEY=nebras_evo_secret_key_2026
    depends_on:
      - redis
    networks:
      - nebras_network

  nginx:
    image: nginx:alpine
    container_name: nebras_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend
    networks:
      - nebras_network

volumes:
  frontend_dist:
  static_volume:
  media_volume:

networks:
  nebras_network:
    driver: bridge