# Generated by Django 5.1.15 on 2026-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='deduction_start_month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='skipped_months',
            field=models.TextField(blank=True, default=''),
        ),
    ]
