# Generated by Django 5.1.15 on 2026-07-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employeeloan_deduction_start_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='approval_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approvers_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='current_approval_step',
            field=models.IntegerField(default=0),
        ),
    ]
