# Generated by Django 5.1.15 on 2026-07-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrun_approval_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
