# Generated by Django 5.1.15 on 2026-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslip_late_deduction_payslip_late_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='absence_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
