# Generated by Django 5.2.15 on 2026-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountingperiod_budget_financestatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaudit',
            name='performed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialclosing',
            name='closed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
