# Generated by Django 5.2.15 on 2026-07-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financialaudit_performed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'verbose_name': 'تصنيف الحساب', 'verbose_name_plural': 'تصنيفات الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['start_date'], 'verbose_name': 'الفترة المحاسبية', 'verbose_name_plural': 'الفترات المحاسبية'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name': 'نوع الحساب', 'verbose_name_plural': 'أنواع الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'البنك', 'verbose_name_plural': 'البنوك والمصارف'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'الحساب البنكي', 'verbose_name_plural': 'الحسابات البنكية للمنشأة'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'الموازنة التقديرية', 'verbose_name_plural': 'الموازنات التقديرية'},
        ),
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'verbose_name': 'بند الموازنة', 'verbose_name_plural': 'بنود الموازنة التقديرية'},
        ),
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name': 'الصندوق المالي', 'verbose_name_plural': 'الصناديق المالية (الخزائن)'},
        ),
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['code'], 'verbose_name': 'الحساب المالي', 'verbose_name_plural': 'شجرة الحسابات (COA)'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['code'], 'verbose_name': 'مركز التكلفة', 'verbose_name_plural': 'مراكز التكلفة'},
        ),
        migrations.AlterModelOptions(
            name='costcenterhierarchy',
            options={'verbose_name': 'هيكل مراكز التكلفة', 'verbose_name_plural': 'هياكل مراكز التكلفة'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'العملة', 'verbose_name_plural': 'العملات'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-rate_date'], 'verbose_name': 'سعر الصرف', 'verbose_name_plural': 'أسعار الصرف'},
        ),
        migrations.AlterModelOptions(
            name='financesettings',
            options={'verbose_name': 'الإعدادات المالية', 'verbose_name_plural': 'إعدادات النظام المالي'},
        ),
        migrations.AlterModelOptions(
            name='financestatistics',
            options={'verbose_name': 'الإحصائيات المالية', 'verbose_name_plural': 'الإحصائيات والملخصات المالية'},
        ),
        migrations.AlterModelOptions(
            name='financialaudit',
            options={'verbose_name': 'سجل تدقيق مالي', 'verbose_name_plural': 'سجلات تدقيق العمليات المالية'},
        ),
        migrations.AlterModelOptions(
            name='financialclosing',
            options={'verbose_name': 'الإغلاق المالي', 'verbose_name_plural': 'عمليات الإغلاق المالي'},
        ),
        migrations.AlterModelOptions(
            name='financialdocument',
            options={'verbose_name': 'المستند المرجعي', 'verbose_name_plural': 'المستندات المالية المرجعية'},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'verbose_name': 'التحويلة المالية', 'verbose_name_plural': 'الحركات والتحويلات المالية'},
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'السنة المالية', 'verbose_name_plural': 'السنوات المالية'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-entry_number'], 'verbose_name': 'قيد اليومية', 'verbose_name_plural': 'قيود اليومية العامة'},
        ),
        migrations.AlterModelOptions(
            name='journalentryline',
            options={'verbose_name': 'سطر القيد', 'verbose_name_plural': 'تفاصيل سطور القيود'},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'verbose_name': 'دفتر الأستاذ', 'verbose_name_plural': 'دفاتر الأستاذ'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['date', 'created_at'], 'verbose_name': 'حركة دفتر الأستاذ', 'verbose_name_plural': 'حركات وقيود دفتر الأستاذ'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'طريقة الدفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
        migrations.AlterModelOptions(
            name='recurringjournal',
            options={'verbose_name': 'القيد الدوري', 'verbose_name_plural': 'القيود الدورية المتكررة'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'الضريبة', 'verbose_name_plural': 'الضرائب المعتمدة'},
        ),
        migrations.AlterModelOptions(
            name='taxgroup',
            options={'verbose_name': 'مجموعة الضرائب', 'verbose_name_plural': 'مجموعات الضرائب'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'السند المالي', 'verbose_name_plural': 'السندات المالية (صرف/قبض)'},
        ),
    ]
