# Generated by Django 5.2.15 on 2026-07-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفترة'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('locked', 'مقفلة')], db_index=True, default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.accountcategory', verbose_name='تصنيف الحساب'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='رمز الحساب'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='is_control_account',
            field=models.BooleanField(default=False, verbose_name='حساب تحكم الرئيسي'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='is_sub_account',
            field=models.BooleanField(default=False, verbose_name='حساب فرعي'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='الاسم العربي'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='الاسم الإنجليزي'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='normal_balance',
            field=models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='طبيعة الحساب'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.chartofaccount', verbose_name='الحساب الأب'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], db_index=True, default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='budget_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الميزانية المخصصة'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='رمز مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='الاسم العربي'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='الاسم الإنجليزي'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.costcenter', verbose_name='المركز الأب'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], db_index=True, default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='type',
            field=models.CharField(choices=[('branch', 'فرع'), ('campus', 'حرم جامعي/مدرسي'), ('department', 'قسم'), ('project', 'مشروع'), ('activity', 'نشاط'), ('custom', 'مخصص')], default='custom', max_length=30, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='السنة المالية الحالية'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم السنة المالية'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('locked', 'مقفلة'), ('reopened', 'معاد فتحها')], db_index=True, default='open', max_length=20, verbose_name='الحالة'),
        ),
    ]
