# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفحص الفعلي'),
        ),
        migrations.AlterField(
            model_name='maintenancevisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الزيارة الفعلي'),
        ),
    ]
