# Generated by Django 5.2.15 on 2026-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_inspection_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='سعر ساعة العمل — يُحتسب به أجر الفني على أوامر العمل'),
        ),
    ]
