# Generated by Django 5.2.15 on 2026-07-04 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title_ar', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('action_type', models.CharField(max_length=50)),
                ('target_route', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nebras_commands',
            },
        ),
        migrations.CreateModel(
            name='CommandAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'nebras_cmd_audit',
            },
        ),
        migrations.CreateModel(
            name='CommandCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'nebras_cmd_categories',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('role_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nebras_cmd_workspaces',
            },
        ),
        migrations.CreateModel(
            name='CommandAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('payload_template', models.JSONField(default=dict)),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_actions',
            },
        ),
        migrations.CreateModel(
            name='CommandAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('alias_ar', models.CharField(max_length=150)),
                ('alias_en', models.CharField(max_length=150)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_aliases',
            },
        ),
        migrations.CreateModel(
            name='CommandAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('execution_count', models.BigIntegerField(default=0)),
                ('avg_execution_ms', models.IntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_analytics',
            },
        ),
        migrations.AddField(
            model_name='command',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='command_center.commandcategory'),
        ),
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_history',
            },
        ),
        migrations.CreateModel(
            name='CommandPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('role_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_permissions',
            },
        ),
        migrations.CreateModel(
            name='CommandShortcut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('key_combination', models.CharField(max_length=50)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_shortcuts',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_favorites',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('title_ar', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='command_center.navigationitem')),
            ],
            options={
                'db_table': 'nebras_cmd_navigation',
            },
        ),
        migrations.CreateModel(
            name='PinnedCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('order', models.IntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_pinned',
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_quick_actions',
            },
        ),
        migrations.CreateModel(
            name='RecentCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('last_executed', models.DateTimeField(auto_now=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.command')),
            ],
            options={
                'db_table': 'nebras_cmd_recent',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFavorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.workspace')),
            ],
            options={
                'db_table': 'nebras_cmd_workspace_favorites',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command_center.workspace')),
            ],
            options={
                'db_table': 'nebras_cmd_workspace_history',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceLayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('layout_json', models.JSONField(default=dict)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='command_center.workspace')),
            ],
            options={
                'db_table': 'nebras_cmd_workspace_layouts',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('theme_preference', models.CharField(default='light', max_length=20)),
                ('active_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='command_center.workspace')),
            ],
            options={
                'db_table': 'nebras_cmd_workspace_settings',
            },
        ),
    ]
