# Generated by Django 5.2.15 on 2026-07-01 13:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('student_file', 'Student File'), ('employee_file', 'Employee File'), ('invoice', 'Invoice'), ('report', 'Report'), ('general', 'General Document')], db_index=True, default='general', max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'file_assets',
                'indexes': [models.Index(fields=['tenant_id', 'category'], name='file_assets_tenant__1c116f_idx')],
            },
        ),
    ]