# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileasset',
            options={'verbose_name': 'ملف مخزّن', 'verbose_name_plural': 'إدارة الملفات والتخزين'},
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='category',
            field=models.CharField(choices=[('student_file', 'ملف طالب'), ('employee_file', 'ملف موظف'), ('invoice', 'فاتورة'), ('report', 'تقرير'), ('general', 'مستند عام')], db_index=True, default='general', max_length=30, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='اسم الملف'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='مسار الملف'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='file_size',
            field=models.BigIntegerField(verbose_name='حجم الملف'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='mime_type',
            field=models.CharField(max_length=100, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='uploaded_by',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='تم الرفع بواسطة'),
        ),
    ]
