# Generated by Django 5.2.15 on 2026-07-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicfeeplan',
            options={'verbose_name': 'خطة الرسوم الأكاديمية', 'verbose_name_plural': 'خطط الرسوم الأكاديمية'},
        ),
        migrations.AlterModelOptions(
            name='billingaudit',
            options={'verbose_name': 'سجل تدقيق الفوترة', 'verbose_name_plural': 'سجلات تدقيق الفوترة'},
        ),
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'verbose_name': 'دورة فوترة', 'verbose_name_plural': 'دورات الفوترة'},
        ),
        migrations.AlterModelOptions(
            name='collectionpolicy',
            options={'verbose_name': 'سياسة تحصيل', 'verbose_name_plural': 'سياسات التحصيل ومتابعة الديون'},
        ),
        migrations.AlterModelOptions(
            name='creditnote',
            options={'verbose_name': 'إشعار دائن', 'verbose_name_plural': 'الإشعارات الدائنة للطلاب'},
        ),
        migrations.AlterModelOptions(
            name='debitnote',
            options={'verbose_name': 'إشعار مدين', 'verbose_name_plural': 'الإشعارات المدينة للطلاب'},
        ),
        migrations.AlterModelOptions(
            name='feecategory',
            options={'verbose_name': 'فئة الرسوم', 'verbose_name_plural': 'فئات الرسوم'},
        ),
        migrations.AlterModelOptions(
            name='feeschedule',
            options={'verbose_name': 'جدول استحقاق الرسوم', 'verbose_name_plural': 'جداول استحقاق الرسوم'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'verbose_name': 'هيكل الرسوم', 'verbose_name_plural': 'هياكل الرسوم'},
        ),
        migrations.AlterModelOptions(
            name='feetype',
            options={'verbose_name': 'نوع الرسوم', 'verbose_name_plural': 'أنواع الرسوم'},
        ),
        migrations.AlterModelOptions(
            name='financialaid',
            options={'verbose_name': 'مساعدة مالية', 'verbose_name_plural': 'المساعدات المالية'},
        ),
        migrations.AlterModelOptions(
            name='financialhold',
            options={'verbose_name': 'حظر مالي', 'verbose_name_plural': 'سجلات الحظر المالي'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'قسط مجدول', 'verbose_name_plural': 'الأقساط المجدولة'},
        ),
        migrations.AlterModelOptions(
            name='installmentplan',
            options={'verbose_name': 'خطة تقسيط', 'verbose_name_plural': 'خطط التقسيط'},
        ),
        migrations.AlterModelOptions(
            name='invoiceadjustment',
            options={'verbose_name': 'تسوية الفاتورة', 'verbose_name_plural': 'تسويات الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='invoicediscount',
            options={'verbose_name': 'خصم الفاتورة', 'verbose_name_plural': 'خصومات الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'بند الفاتورة', 'verbose_name_plural': 'بنود الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='latefeerule',
            options={'verbose_name': 'قاعدة غرامة تأخير', 'verbose_name_plural': 'قواعد غرامات التأخير'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'تخصيص سداد', 'verbose_name_plural': 'تخصيصات السداد'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'إيصال سداد', 'verbose_name_plural': 'إيصالات تحصيل الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'مبلغ مسترد', 'verbose_name_plural': 'المبالغ المستردة للطلاب'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'منحة دراسية', 'verbose_name_plural': 'المنح الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='scholarshiprule',
            options={'verbose_name': 'قاعدة المنح', 'verbose_name_plural': 'قواعد المنح الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'verbose_name': 'كشف حساب', 'verbose_name_plural': 'كشوفات الحساب التاريخية'},
        ),
        migrations.AlterModelOptions(
            name='studentbillingaccount',
            options={'verbose_name': 'حساب فوترة الطالب', 'verbose_name_plural': 'حسابات فوترة الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='studentfinancesettings',
            options={'verbose_name': 'إعدادات مالية الطلاب', 'verbose_name_plural': 'إعدادات مالية الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='studentinvoice',
            options={'ordering': ['-issue_date', '-invoice_number'], 'verbose_name': 'فاتورة الطالب', 'verbose_name_plural': 'فواتير الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='studentreceivable',
            options={'verbose_name': 'مستحق طالب', 'verbose_name_plural': 'حسابات القبض والمستحقات'},
        ),
    ]
