# Generated by Django 5.2.15 on 2026-07-14 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_finance', '0002_alter_academicfeeplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('student_id', models.UUIDField(db_index=True)),
                ('submitted_by_user_id', models.UUIDField(blank=True, help_text='مستخدم ولي الأمر مقدّم الطلب', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_name', models.CharField(default='بنك الخرطوم', max_length=100)),
                ('transfer_reference', models.CharField(help_text='الرقم المرجعي للتحويل (عبر بنكك)', max_length=50)),
                ('transfer_date', models.DateField()),
                ('sender_name', models.CharField(blank=True, help_text='اسم صاحب الحساب المُحوِّل', max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_attachment', models.FileField(upload_to='student_finance/online_payments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'معلّق قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('receipt_id', models.UUIDField(blank=True, help_text='إيصال القبض المُنشأ عند الاعتماد', null=True)),
                ('posted_to_gl', models.BooleanField(default=False, help_text='هل رُحّل القيد المحاسبي في دفتر الأستاذ')),
                ('student_billing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_requests', to='student_finance.studentbillingaccount')),
            ],
            options={
                'verbose_name': 'طلب سداد أونلاين',
                'verbose_name_plural': 'طلبات السداد الأونلاين',
                'db_table': 'nebras_online_payment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
