# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_finance', '0003_onlinepaymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
