# Generated by Django 5.1.15 on 2026-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_finance', '0004_alter_statement_statement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='سبب عكس أو إلغاء السند', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversal_journal_entry_id',
            field=models.UUIDField(blank=True, help_text='القيد العكسي المولد في دفتر الأستاذ', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت العكس', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversed_by',
            field=models.UUIDField(blank=True, help_text='المستخدم الذي قام بالعكس', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل ومقفل في الصندوق'), ('cancelled', 'ملغي'), ('reversed', 'معكوس')], db_index=True, default='draft', max_length=20),
        ),
    ]
