# Generated by Django 5.1.15 on 2026-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_finance', '0005_add_receipt_reversal_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'base_manager_name': 'objects', 'verbose_name': 'بند الفاتورة', 'verbose_name_plural': 'بنود الفواتير'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_unlocked_by',
            field=models.UUIDField(blank=True, help_text='المدير الذي قام بفتح القفل', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='admin_unlocked_until',
            field=models.DateTimeField(blank=True, help_text='صلاحية فتح قفل التعديل والحذف بعد 24 ساعة بأمر الأدمن', null=True),
        ),
    ]
