# Generated by Django 5.2.15 on 2026-07-05 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowdefinition',
            options={'verbose_name': 'تعريف مسار عمل', 'verbose_name_plural': 'تعريفات مسارات العمل'},
        ),
        migrations.AlterModelOptions(
            name='workflowhistory',
            options={'verbose_name': 'سجل حركة مسار عمل', 'verbose_name_plural': 'سجل حركات مسارات العمل'},
        ),
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'verbose_name': 'مثيل مسار عمل', 'verbose_name_plural': 'مثيلات مسارات العمل'},
        ),
        migrations.AlterModelOptions(
            name='workflowstate',
            options={'verbose_name': 'حالة مسار عمل', 'verbose_name_plural': 'حالات مسارات العمل'},
        ),
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'verbose_name': 'انتقال مسار عمل', 'verbose_name_plural': 'انتقالات مسارات العمل'},
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع النموذج المستهدف'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='action_by',
            field=models.UUIDField(verbose_name='تم بواسطة'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='action_taken',
            field=models.CharField(max_length=100, verbose_name='الإجراء المتخذ'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='from_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='workflow.workflowstate', verbose_name='من حالة'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowinstance', verbose_name='مثيل مسار العمل'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='workflow.workflowstate', verbose_name='إلى حالة'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع النموذج'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowstate', verbose_name='الحالة الحالية'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='object_id',
            field=models.UUIDField(verbose_name='معرف السجل'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowdefinition', verbose_name='مسار العمل'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='code',
            field=models.CharField(max_length=50, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='حالة نهائية'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='is_initial',
            field=models.BooleanField(default=False, verbose_name='حالة أولية'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition', verbose_name='مسار العمل'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='workflow.workflowstate', verbose_name='من حالة'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='permission_required',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الصلاحية المطلوبة'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='workflow.workflowstate', verbose_name='إلى حالة'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='trigger_action',
            field=models.CharField(max_length=100, verbose_name='إجراء التنفيذ'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition', verbose_name='مسار العمل'),
        ),
    ]
