# Generated by Django 5.2.15 on 2026-07-02 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('employee_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('national_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='active', max_length=30)),
            ],
            options={
                'db_table': 'nebras_employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='employees.employee')),
            ],
            options={
                'db_table': 'nebras_employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='employees.employee')),
            ],
            options={
                'db_table': 'nebras_employee_status_history',
            },
        ),
    ]