# Generated by Django 5.1.15 on 2026-07-22 00:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_joining_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'موظف / معلم', 'verbose_name_plural': 'الموظفون والمعلمون'},
        ),
        migrations.AddField(
            model_name='employee',
            name='admin_manager_approval',
            field=models.BooleanField(default=True, verbose_name='اعتماد المدير الإداري'),
        ),
        migrations.AddField(
            model_name='employee',
            name='admin_manager_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اعتماد المدير الإداري'),
        ),
        migrations.AddField(
            model_name='employee',
            name='agreed_to_bylaws',
            field=models.BooleanField(default=True, verbose_name='إقرار والتزام بلائحة العمل العامة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=12, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='children_count',
            field=models.IntegerField(default=0, verbose_name='عدد الأبناء'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='communication_allowance',
            field=models.DecimalField(decimal_places=2, default=40000.0, max_digits=12, verbose_name='بدل اتصال وانترنت'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد (مثال 31/7/2026)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بدء العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الخصومات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_exempt',
            field=models.BooleanField(default=True, verbose_name='معفى من النوبتجية (Duty)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_kinship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم آخر يمكن الرجوع إليه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الكلية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='general_manager_approval',
            field=models.BooleanField(default=True, verbose_name='اعتماد المدير العام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='general_manager_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اعتماد المدير العام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المنزل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=350000.0, max_digits=12, verbose_name='المستحق صرفه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_tasks_activities',
            field=models.TextField(blank=True, null=True, verbose_name='أي مهام أخرى أو أنشطة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف 2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف 3'),
        ),
        migrations.AddField(
            model_name='employee',
            name='prominent_teacher_friend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم أقرب معلم بارز'),
        ),
        migrations.AddField(
            model_name='employee',
            name='representation_allowance',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=12, verbose_name='بدل تمثيل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school_manager_approval',
            field=models.BooleanField(default=True, verbose_name='اعتماد مدير المدرسة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school_manager_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ اعتماد مدير المدرسة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التخصص الدقيق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='square_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المربع'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teacher_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ توقيع المعلم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teaching_subject_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المادة (1)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teaching_subject_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المادة (2)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='teaching_subject_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المادة (3)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اللقب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=80000.0, max_digits=12, verbose_name='بدل ترحيل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='university_institute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجامعة / المعهد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_lesson_quota',
            field=models.IntegerField(default=23, verbose_name='نصاب الحصص الأسبوعي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الواتساب الرسمي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان السكني الشامل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='التعليم والإشراف', max_length=100, verbose_name='القسم الإداري'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(default='Full-time', max_length=50, verbose_name='نوع التوظيف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_ar',
            field=models.CharField(max_length=255, verbose_name='الاسم رباعياً بالعربية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المباشرة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='رقم الهاتف الرئيسية (1)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='سوداني', max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='معلم', max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, default='مسلم', max_length=100, null=True, verbose_name='الديانة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=30, verbose_name='الحالة الوظيفية'),
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ السلفية')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب السلفية')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ طلب السلفية')),
                ('status', models.CharField(default='pending', max_length=30, verbose_name='حالة السلفية')),
                ('repayment_months', models.IntegerField(default=2, verbose_name='عدد شهور الاستقطاع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبلغ المسدد')),
                ('school_manager_approved', models.BooleanField(default=False, verbose_name='موافقة مدير المدرسة')),
                ('finance_approved', models.BooleanField(default=False, verbose_name='موافقة الإدارة المالية')),
                ('general_manager_approved', models.BooleanField(default=False, verbose_name='موافقة الإدارة العامة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفية موظف',
                'verbose_name_plural': 'سلفيات الموظفين والمعلمين',
                'db_table': 'nebras_employee_advances',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDependent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم رباعياً')),
                ('academic_stage', models.CharField(max_length=100, verbose_name='المرحلة الدراسية')),
                ('grade_level', models.CharField(max_length=100, verbose_name='الصف الدراسي')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='نسبة الخصم المستحقة %')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'أبناء الموظف بالمدرسة',
                'verbose_name_plural': 'سجل أبناء الموظفين بالمدرسة',
                'db_table': 'nebras_employee_dependents',
            },
        ),
        migrations.CreateModel(
            name='EmployeePriorExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('school_name', models.CharField(max_length=255, verbose_name='آخر مدرسة عمل بها')),
                ('time_period', models.CharField(max_length=150, verbose_name='الفترة الزمنية والتاريخ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_experiences', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'خبرة مدرسية سابقة',
                'verbose_name_plural': 'الخبرات المدرسية السابقة',
                'db_table': 'nebras_employee_prior_experiences',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('ref_name', models.CharField(max_length=255, verbose_name='اسم المعلم المرجع بالمدرسة')),
                ('ref_phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مرجع معلم بالمدرسة',
                'verbose_name_plural': 'المعرفون والمرجعيات الشخصية',
                'db_table': 'nebras_employee_references',
            },
        ),
    ]
