# Generated by Django 5.1.15 on 2026-07-22 00:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeadvance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeedependent',
            options={'verbose_name': 'ابن/ابنة الموظف', 'verbose_name_plural': 'أبناء الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='employeepriorexperience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeereference',
            options={},
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='biography',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='employeeadvance',
            name='finance_approved',
        ),
        migrations.RemoveField(
            model_name='employeeadvance',
            name='general_manager_approved',
        ),
        migrations.RemoveField(
            model_name='employeeadvance',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='employeeadvance',
            name='school_manager_approved',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employeestatushistory',
            name='change_reason',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف الرئيسية (1)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='السبب والغرض'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='repayment_months',
            field=models.IntegerField(default=2, verbose_name='عدد أشهُر الخصم'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='status',
            field=models.CharField(default='approved', max_length=30, verbose_name='حالة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='academic_stage',
            field=models.CharField(default='المرحلة الابتدائية', max_length=100, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='نسبة التخفيض %'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.employee', verbose_name='الموظف/المعلم'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='اسم التلميذ'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='grade_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='employeedependent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الإعفاء'),
        ),
        migrations.AlterField(
            model_name='employeepriorexperience',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='اسم المدرسة/المؤسسة'),
        ),
        migrations.AlterField(
            model_name='employeepriorexperience',
            name='time_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفترة الزمنية والتاريخ'),
        ),
        migrations.AlterField(
            model_name='employeereference',
            name='ref_name',
            field=models.CharField(max_length=255, verbose_name='اسم المعلم المرجع'),
        ),
        migrations.AlterField(
            model_name='employeereference',
            name='ref_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
