# Generated by Django 5.1.15 on 2026-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeadvance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'موظف / معلم', 'verbose_name_plural': 'الموظفون والمعلمون'},
        ),
        migrations.AddField(
            model_name='employee',
            name='gatekeeper_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم البواب'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='is_fully_exempt',
            field=models.BooleanField(default=False, verbose_name='معفى كلياً من الرسوم الدراسية'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='relation_type',
            field=models.CharField(choices=[('child', 'ابن/ابنة'), ('relative', 'قريب من الدرجة الأولى')], db_index=True, default='child', max_length=20, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='employeepriorexperience',
            name='country',
            field=models.CharField(db_index=True, default='السودان', max_length=100, verbose_name='البلد'),
        ),
    ]
