# Generated by Django 5.1.15 on 2026-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_options_employee_gatekeeper_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedependent',
            name='linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تأكيد الربط'),
        ),
        migrations.AddField(
            model_name='employeedependent',
            name='student_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='الطالب المرتبط'),
        ),
    ]
