# Generated by Django 5.2.15 on 2026-07-10 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='track',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
