# Generated by Django 5.1.15 on 2026-09-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_grade_subject_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='passing_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=5, null=True),
        ),
    ]
