# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinicaudit_clinicsettings_clinicstatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicvisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الزيارة'),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفحص'),
        ),
        migrations.AlterField(
            model_name='heightweightrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ القياس'),
        ),
        migrations.AlterField(
            model_name='isolationcase',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الدخول في العزل'),
        ),
        migrations.AlterField(
            model_name='medicalscreening',
            name='screening_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفحص العام'),
        ),
        migrations.AlterField(
            model_name='medicationdispense',
            name='dispense_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الصرف'),
        ),
    ]
