# Generated by Django 5.2.15 on 2026-07-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinicvisit_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicvisit',
            name='patient_type',
            field=models.CharField(choices=[('student', 'طالب'), ('employee', 'موظف/معلم')], db_index=True, default='student', max_length=20, verbose_name='نوع المريض — يحدّد أي سجل يُقرأ منه الاسم'),
        ),
        migrations.AddField(
            model_name='medicalleave',
            name='patient_type',
            field=models.CharField(choices=[('student', 'طالب'), ('employee', 'موظف/معلم')], db_index=True, default='student', max_length=20, verbose_name='نوع المريض — يحدّد أي سجل يُقرأ منه الاسم'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='patient_type',
            field=models.CharField(choices=[('student', 'طالب'), ('employee', 'موظف/معلم')], db_index=True, default='student', max_length=20, verbose_name='نوع المريض — يحدّد أي سجل يُقرأ منه الاسم'),
        ),
    ]
