# Generated by Django 5.1.15 on 2026-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='school_gender_type',
            field=models.CharField(choices=[('boys', 'مدرسة بنين'), ('girls', 'مدرسة بنات'), ('coed', 'مشتركة (بنين وبنات)')], db_index=True, default='coed', max_length=20),
        ),
    ]
