# Generated by Django 5.2.15 on 2026-07-01 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tenants/icons/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='tenants/stamps/')),
                ('primary_color', models.CharField(default='#1e3a8a', max_length=7)),
                ('secondary_color', models.CharField(default='#10b981', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
    ]