# Generated by Django 5.1.15 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stamp_academic',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/stamps/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stamp_finance',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/stamps/'),
        ),
    ]
