# Generated by Django 5.1.15 on 2026-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_remove_studentprofile_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfamilyrelation',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الواتساب المعتمد'),
        ),
    ]
