# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'verbose_name': 'تقرير محفوظ', 'verbose_name_plural': 'التقارير المحفوظة'},
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_by_user',
            field=models.UUIDField(db_index=True, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='query_params',
            field=models.JSONField(default=dict, verbose_name='معايير الاستعلام'),
        ),
    ]
