# Generated by Django 5.1.15 on 2026-07-28 09:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('method', models.CharField(choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('card', 'بطاقة'), ('manual', 'تسوية يدوية')], default='bank_transfer', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('transfer_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_attachment', models.FileField(blank=True, null=True, upload_to='saas_billing/payment_submissions/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'معلّق قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('submitted_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='saas_billing.invoice')),
                ('payment', models.ForeignKey(blank=True, help_text='الدفعة المُنشأة عند الاعتماد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='saas_billing.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_payment_submissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'طلب سداد اشتراك',
                'verbose_name_plural': 'طلبات سداد الاشتراك',
                'db_table': 'saas_payment_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
