# Generated by Django 5.1.15 on 2026-07-28 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0002_paymentsubmission'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSignupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(db_index=True, help_text='النطاق الفرعي المطلوب', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'معلّق قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_tenant', models.ForeignKey(blank=True, help_text='المستأجر المُنشأ عند الاعتماد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='tenants.tenant')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='saas_billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'طلب انضمام مدرسة',
                'verbose_name_plural': 'طلبات انضمام المدارس',
                'db_table': 'saas_tenant_signup_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
