# Generated by Django 5.2.15 on 2026-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationchannel',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
