# Generated by Django 5.2.15 on 2026-07-18 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_driver_fleet_fleetstatistics_fuelstation_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التخصيص'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ تعبئة الوقود'),
        ),
        migrations.AlterField(
            model_name='odometerreading',
            name='reading_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ القراءة'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الفحص'),
        ),
    ]
