# Generated by Django 5.1.15 on 2026-09-06 10:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetassignment_assigned_date_and_more'),
        ('transport', '0003_alter_driverassignment_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='geofence_radius_meters',
            field=models.IntegerField(default=100, verbose_name='نطاق الاستشعار الجغرافي (متر)'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=15.5007, max_digits=10, null=True, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=32.5599, max_digits=10, null=True, verbose_name='خط الطول (Longitude)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monthly_rent_sdg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قيمة الإيجار الشهري (ج.س)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم حساب بنكك / الهاتف المسجل'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_bank_name',
            field=models.CharField(blank=True, default='بنك الخرطوم (تطبيق بنكك)', max_length=100, null=True, verbose_name='البنك المعتمد للسداد'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم صاحب/مالك الحافلة'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوطني للمالك'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف مالك الحافلة'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('contracted', 'مستأجرة بعقد اتفاق مع المالك'), ('owned', 'مملوكة للمدرسة بالكامل')], default='contracted', max_length=20, verbose_name='نوع الملكية'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rent_payment_method',
            field=models.CharField(choices=[('bankak', 'تطبيق بنكك - بنك الخرطوم'), ('fawry', 'تطبيق فوري - بنك فيصل'), ('cash', 'نقداً (كاش)'), ('cheque', 'شيك مصرفي')], default='bankak', max_length=50, verbose_name='طريقة سداد الإيجار'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_details', to='assets.asset', verbose_name='الأصل المقابل (للمركبات المملوكة)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50, verbose_name='رقم لوحة المركبة (مثال: خ 5 / 12345)'),
        ),
        migrations.CreateModel(
            name='BusRentalAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=150, verbose_name='اسم صاحب/مالك الحافلة')),
                ('owner_phone', models.CharField(max_length=50, verbose_name='هاتف المالك')),
                ('owner_national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوطني للمالك')),
                ('monthly_rent_sdg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الإيجار الشهري (ج.س)')),
                ('payment_method', models.CharField(choices=[('bankak', 'تطبيق بنكك - بنك الخرطوم'), ('fawry', 'تطبيق فوري - بنك فيصل'), ('cash', 'نقداً (كاش)'), ('cheque', 'شيك مصرفي')], default='bankak', max_length=50, verbose_name='طريقة السداد المعتمدة')),
                ('bank_name', models.CharField(default='بنك الخرطوم (تطبيق بنكك)', max_length=100, verbose_name='اسم البنك')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم حساب بنكك / الهاتف المسجل')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ بدء الاتفاق')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاتفاق')),
                ('status', models.CharField(choices=[('active', 'ساري ومفعّل'), ('expired', 'منتهي الصلاحية'), ('terminated', 'ملغى / مفسوخ')], default='active', max_length=20, verbose_name='حالة العقد')),
                ('terms_notes', models.TextField(blank=True, null=True, verbose_name='شروط الاتفاق والمسؤوليات والصيانة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='transport.vehicle', verbose_name='الحافلة')),
            ],
            options={
                'verbose_name': 'عقد اتفاق حافلة مستأجرة',
                'verbose_name_plural': 'عقود اتفاقات الحافلات المستأجرة',
                'db_table': 'nebras_transport_bus_agreements',
            },
        ),
        migrations.CreateModel(
            name='BusRentalPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('period_label', models.CharField(max_length=100, verbose_name='الفترة / الشهر (مثال: إيجار شهر سبتمبر 2026)')),
                ('amount_sdg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المسدد (ج.س)')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السداد')),
                ('payment_method', models.CharField(choices=[('bankak', 'تطبيق بنكك - بنك الخرطوم'), ('fawry', 'تطبيق فوري - بنك فيصل'), ('cash', 'نقداً (كاش)'), ('cheque', 'شيك مصرفي')], default='bankak', max_length=50, verbose_name='طريقة السداد')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم إشعار تحويل بنكك / السند')),
                ('status', models.CharField(choices=[('paid', 'تم السداد بنجاح'), ('pending', 'قيد الصرف والاعتماد')], default='paid', max_length=20, verbose_name='حالة الدفعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الصرف')),
                ('journal_entry_id', models.UUIDField(blank=True, null=True, verbose_name='قيد اليومية المحاسبي المقابل بالمالية')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.busrentalagreement', verbose_name='عقد الاتفاق')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_payments', to='transport.vehicle', verbose_name='الحافلة')),
            ],
            options={
                'verbose_name': 'سداد إيجار حافلة',
                'verbose_name_plural': 'سجلات سداد إيجارات الحافلات المستأجرة',
                'db_table': 'nebras_transport_bus_rental_payments',
            },
        ),
        migrations.CreateModel(
            name='VehicleGPSLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض (Latitude)')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول (Longitude)')),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='السرعة (كم/س)')),
                ('heading', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='زاوية الاتجاه')),
                ('battery_level', models.IntegerField(blank=True, default=100, null=True, verbose_name='شحنة بطارية جهاز السائق %')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت التسجيل الميداني')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_breadcrumbs', to='transport.trip', verbose_name='الرحلة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='transport.vehicle', verbose_name='الحافلة')),
            ],
            options={
                'verbose_name': 'إحداثية GPS',
                'verbose_name_plural': 'إحداثيات وسجل تتبع GPS الحافلات',
                'db_table': 'nebras_transport_vehicle_gps_locations',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
