# Generated by Django 5.2.15 on 2026-07-02 12:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('arabic_full_name', models.CharField(max_length=255)),
                ('english_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('national_id', models.CharField(db_index=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year_id', models.UUIDField(db_index=True)),
                ('applying_grade_id', models.UUIDField(db_index=True)),
                ('applying_section_id', models.UUIDField(blank=True, null=True)),
                ('application_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=150, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admission_applicants',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('relationship', models.CharField(choices=[('father', 'أب'), ('mother', 'أم'), ('guardian', 'ولي أمر'), ('sponsor', 'كفيل')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('national_id', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('emergency_contact', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(default='phone', max_length=20)),
                ('financial_responsibility', models.BooleanField(default=False)),
                ('legal_guardian', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admission_guardians',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('interviewer_id', models.UUIDField(db_index=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admission_interviews',
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('exam_type', models.CharField(max_length=100)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('result_status', models.CharField(default='pending', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admission_placement_tests',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('document_name', models.CharField(max_length=255)),
                ('file_asset_id', models.UUIDField()),
                ('verification_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'تم التحقق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admission_documents',
            },
        ),
    ]