# Generated by Django 5.2.15 on 2026-07-08 11:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(db_index=True, default=False)),
                ('academic_year_id', models.UUIDField(blank=True, null=True)),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('allowed_grade_ids', models.JSONField(blank=True, default=list)),
                ('terms', models.TextField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_message', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'admission_settings',
            },
        ),
    ]
