# Generated by Django 5.2.15 on 2026-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsettings',
            name='auto_close_when_full',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='grade_seats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
