# Generated by Django 5.1.15 on 2026-07-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionsettings_auto_close_when_full_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionsettings',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='placementtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='requireddocument',
            options={'ordering': ['-created_at']},
        ),
    ]
