# Generated by Django 5.1.15 on 2026-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_guardian_phone2_guardian_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsettings',
            name='aptitude_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='aptitude_total_pass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
