# Generated by Django 5.1.15 on 2026-07-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admissionsettings_aptitude_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsettings',
            name='annual_tuition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='fee_currency',
            field=models.CharField(default='جنيه', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='fee_installments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='fee_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
