# Generated by Django 5.2.15 on 2026-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantsetting',
            options={'verbose_name': 'إعداد مستأجر', 'verbose_name_plural': 'إعدادات المستأجرين'},
        ),
        migrations.AlterField(
            model_name='tenantsetting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='tenantsetting',
            name='group',
            field=models.CharField(db_index=True, max_length=50, verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='tenantsetting',
            name='key',
            field=models.CharField(db_index=True, max_length=100, verbose_name='المفتاح'),
        ),
        migrations.AlterField(
            model_name='tenantsetting',
            name='value',
            field=models.JSONField(verbose_name='القيمة'),
        ),
    ]
