# Generated by Django 5.2.15 on 2026-07-02 20:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('employee_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('teacher_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('national_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ar', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('branch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('current_position', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='draft', max_length=30)),
            ],
            options={
                'db_table': 'nebras_faculty_members',
            },
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_faculty_qualifications',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('academic_year_id', models.UUIDField(db_index=True)),
                ('term_id', models.UUIDField(db_index=True)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('section_id', models.UUIDField(db_index=True)),
                ('weekly_hours', models.IntegerField(default=4)),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_faculty_assignments',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('working_day', models.CharField(max_length=20)),
                ('max_daily_hours', models.IntegerField(default=8)),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_faculty_availability',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('specialization', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('teaching_philosophy', models.TextField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_faculty_teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeachingLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_status', models.CharField(default='active', max_length=50)),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='faculty.facultymember')),
            ],
            options={
                'db_table': 'nebras_faculty_licenses',
            },
        ),
    ]